"""DB inicial

Revision ID: 21b08a33fa07
Revises: 
Create Date: 2023-02-21 21:49:46.083117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21b08a33fa07'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadoSolicitudes')
    op.create_table('estadoSolicitudes',
    sa.Column('fkIdSolicitud', sa.Integer(), nullable=False),
    sa.Column('idInternoDepto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idModificacion', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=20), nullable=False),
    sa.Column('descripcionProceso', sa.String(length=100), nullable=False),
    sa.Column('fechaModificacion', sa.Date(), nullable=False),
    sa.Column('designadoA', sa.String(length=60), nullable=False),
    sa.Column('estadoActual', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fkIdSolicitud'], ['solicitudes.idSolicitud'], ),
    sa.ForeignKeyConstraint(['nombreUsuario'], ['usuarios.nombreUsuario'], ),
    sa.PrimaryKeyConstraint('fkIdSolicitud', 'idModificacion'),
    sa.UniqueConstraint('idInternoDepto')
    )
    op.drop_table('estadosolicitudes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estadosolicitudes',
    sa.Column('fkIdSolicitud', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('idInternoDepto', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('idModificacion', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('nombreUsuario', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('descripcionProceso', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('fechaModificacion', sa.DATE(), nullable=False),
    sa.Column('designadoA', mysql.VARCHAR(length=60), nullable=False),
    sa.Column('estadoActual', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['fkIdSolicitud'], ['solicitudes.idSolicitud'], name='estadosolicitudes_ibfk_1'),
    sa.ForeignKeyConstraint(['nombreUsuario'], ['usuarios.nombreUsuario'], name='estadosolicitudes_ibfk_2'),
    sa.PrimaryKeyConstraint('fkIdSolicitud', 'idModificacion'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('estadoSolicitudes')
    # ### end Alembic commands ###
